name: GitHub Activity Card
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate activity card
        uses: jeremydmiller/github-profile-activity-readme@v0.0.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update activity stats"
          git push
        continue-on-error: true
