name: Generate GitHub Activity Graph

on:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight
  workflow_dispatch:

jobs:
  generate-activity-graph:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate activity graph
        uses: Ashutosh00710/github-readme-activity-graph@v1.0.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit activity graph
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add activity-graph.svg
          git commit -m "Update activity graph" || echo "No changes to commit"
          git push
