name: Generate Contribution Snake

on:
  schedule:
    - cron: '0 0 * * *'  # daily at midnight UTC
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate snake animation
        uses: Platane/snk@v2
        with:
          github_user_name: tushargoyalbtp

      - name: Commit updated snake animation
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add output/github-contribution-grid-snake.svg
          git diff --cached --quiet || git commit -m "Update snake animation"
          git push
