name: snake

on:
  schedule:
    - cron: '0 0 * * *'  # daily at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate contribution snake animation
        uses: Platane/snk@v2.4.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit snake animation
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add output/github-contribution-grid-snake.svg
          git commit -m "Update contribution snake"
          git push
